apiVersion: v1
kind: Secret
metadata:
  name: buildstock-secrets
type: Opaque
data:
  DB_USER: YnVpbGRzdG9ja191c2Vy
  DB_PASS: YnVpbGRzdG9ja19wYXNzXzIwMjY=
  DB_NAME: YnVpbGRzdG9ja19kYg==
  REDIS_PASS: cmVkaXNfc2VjcmV0X3Bhc3M=
  JWT_SECRET: YnVpbGRzdG9jay1jaGFuZ2UtdGhpcy1zZWNyZXQtaW4tcHJvZHVjdGlvbg==
  MINIO_USER: YnVpbGRzdG9ja19hZG1pbg==
  MINIO_PASS: bWluaW9fc2VjcmV0X3Bhc3NfMjAyNg==
